### ISSUE TITLE
裏表紙イラストの変更

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#1]
現在ポテト噴霧栽培のgif アニメーションを裏表紙に配してますが、今の所本文と関係がないので差替が望ましいと考えます。

**Comment by busyoucow** [comment]
NT東京版では表紙裏表紙共に変更する予定でした。そのため、それまでに差し替え改善します。

**Comment by busyoucow** [comment]
差し替え完了しました。
https://github.com/busyoucow/spacefarm/commit/013d69239c100bc5f7e8f8e49e6b499dbc4611a2
