### ISSUE TITLE
「総統」呼称について

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#12]
# 総統の所属
「秋葉原ロボット部総統」は間違い。

# 著者の所属

今後の発売は「オープンフォース」に沿うことになります。

「秋葉原ロボット部」を「オープンフォース」に変更するか、
著者を「秋葉原ロボット部 @busyoucouw」のままとして「秘密結社オープンフォース」を共著者あるいは編集者とするかとするのはどうですか。

# 総統の呼称

唐突に「総統」が出てくるので「総統」を使うには説明が必要。あるいは最初に使う言葉を「秘密結社総統」への変更が必要。

**Comment by busyoucow** [comment]
修正しました。

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/7effd54d7572ea870ecd596dc96d86746bc1ff95
修正済みです。
