### ISSUE TITLE
「宇宙生活で不足するタンパク質」セクション

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#13]
https://github.com/busyoucow/spacefarm/blob/2273dbc6a3e587e323f2b31e286f6b508b9f5515/spaceFarm.md#%E5%AE%87%E5%AE%99%E7%94%9F%E6%B4%BB%E3%81%A7%E4%B8%8D%E8%B6%B3%E3%81%99%E3%82%8B%E3%82%BF%E3%83%B3%E3%83%91%E3%82%AF%E8%B3%AA
説明をリスト化

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/a95cca9e4492a69152519bb35211d237abcfb5d6
一部リスト化
