### ISSUE TITLE
「酵母で補うには」セクション

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#14]
何を酵母で補うか説明が必要
https://github.com/busyoucow/spacefarm/blob/2273dbc6a3e587e323f2b31e286f6b508b9f5515/spaceFarm.md#%E9%85%B5%E6%AF%8D%E3%81%A7%E8%A3%9C%E3%81%86%E3%81%AB%E3%81%AF

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/a95cca9e4492a69152519bb35211d237abcfb5d6
説明を一部修正。
