### ISSUE TITLE
植物性タンパク質が何が問題かを明示

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#16]
> 弊害として植物性タンパク質偏重による身体不調も問題視されている。

何が問題なのか明確に。

https://github.com/busyoucow/spacefarm/blob/2273dbc6a3e587e323f2b31e286f6b508b9f5515/spaceFarm.md#%E3%82%BF%E3%83%B3%E3%83%91%E3%82%AF%E8%B3%AA%E3%81%AE%E7%A2%BA%E4%BF%9D

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/95e5829c1080534cd1de218c0745879fa89746e3
こちらにて大豆と枝豆のイソフラボン量とその弊害により酵母菌を活用する旨記載
