### ISSUE TITLE
作物の選択 セクション中のリスト

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#2]
https://github.com/busyoucow/spacefarm/blob/main/spaceFarm.md#%E4%BD%9C%E7%89%A9%E3%81%AE%E9%81%B8%E6%8A%9E

の
「現代の地上で揃えるならば」
がリストに入っている

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/1a9684aab300947e93369ea2576b6f6121a41bda

にて、修正しました。
