### ISSUE TITLE
README

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#3]
現在の README が本文の写しになっているので、サイトを訪れた人に以下のようなものを説明するように変更する必要があります。

- プロジェクトの概略説明
- 紙本との関連性
- ライセンス
- 疑問・質問点について

**Comment by nanbuwks** [comment]
こちらで口頭で説明してもらった内容を反映しました。新たに追加された「疑問・質問」の章の記述をお願いします。

**Comment by busyoucow** [comment]
修正しました。
https://github.com/busyoucow/spacefarm/commit/a26273386f578071024bb0f70cafeedac76abd0c
