### ISSUE TITLE
レポジトリルートディレクトリ中の不要ファイル

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#4]
nuts_himawari.png
などの使用していないファイルがルートディレクトリに存在しています。
今後も使用していなければ git rm  で処理、今後も使う可能性がある場合は git mv コマンドで images ディレクトリに移動する必要があります。

**Comment by busyoucow** [comment]
nuts_himawari-1.png
nuts_himawari-2.png
nuts_himawari-3.png
nuts_himawari.png
これらは使用していませんので削除
PXL_20240825=033016980.jpg
spaceFarm.jpeg
spaceFarm.png
SpaceRecipe01-001.zip
これらは他で使用している可能性があるため移動

**Comment by nanbuwks** [comment]
zip ファイルが含まれていて これをレポジトリに含んでいると負荷が重いので 履歴からも同時に削除する必要があります。
この資料を元に削除を行いましょう。
https://qiita.com/go_astrayer/items/6e39d3ab16ae8094496c
> これらは他で使用している可能性があるため

これら4ファイルすべて使用していませんでした。同様に削除しましょう。

**Comment by busyoucow** [comment]
作業完了しました。
