### ISSUE TITLE
前提条件の記述

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#5]
- 月面でもなく島三号内面でもないこと
- 反重力装置や亜空間収容、万能バイオ生物などは無いということ

なぜ、このような前提となるのかの説明が必要。

**Comment by busyoucow** [comment]
島三号は実現はおろか計画すら進んでおりません。
半重力装置は開発機関の協力はおろか存在すら掴めていません。
亜空間収容は2000年以降のアニメにはなかなか登場しない設定です。もちろん現実化もロボットの時空転移記録もありません。
万能バイオ生物は遺伝子操作による新生物生成被害が蚊の例を挙げるまでもなく存在する為不可です。
これらの説明は同人誌の方向性（トンデモ考察同人誌ではありません）及び紙面の都合により割愛させていただきます。

**Comment by nanbuwks** [comment]
月面、島三号内面、反重力装置や亜空間収容、万能バイオ生物 の説明が必要というIssue ではありません。
なぜ、そういった技術を使わないかの説明です。
反重力装置を使えば簡単じゃん、というナンセンスな感想を最初に封じておきませんか。

**Comment by busyoucow** [comment]
冒頭に記述を追加しました。

**Comment by busyoucow** [comment]
コミットは
https://github.com/busyoucow/spacefarm/commit/b37065f3b47a9887036fec17803e0777fb90104c
です。
