### ISSUE TITLE
デブリについての基本的な記述と本論の展開について

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#6]
「デブリ速度は10km/s」https://github.com/busyoucow/spacefarm/blob/main/spaceFarm.md#%E3%83%87%E3%83%96%E3%83%AA%E9%80%9F%E5%BA%A6%E3%81%AF10kms

のセクションの記述について。

> 戦車砲徹甲弾は2km/s
> 完全に防御しきるのは困難 デブリ類外壁貫通確率は年間1% JAXAのISSモジュール「きぼう」運用データ
> 年間10個は貫通 / バルーンプラント1000個

- 引用の記法に修正する必要があります
- 数字の論拠を示す必要があります
- 論理の展開を書き示す必要があります

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/e73b97b011e26a9f257dbb627fcaece39df5b119
引用部分を修正しました。

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/e73b97b011e26a9f257dbb627fcaece39df5b119
出展記述を変更しました。

**Comment by nanbuwks** [comment]
数字と論理については、数字の計算は別の稿に分けたほうが良さそうですね。一旦クローズしてその後に新たなIssie を出すことにします。
