### ISSUE TITLE
作物の選択 セクション

### ISSUE THREAD

**Issue by nanbuwks** [busyoucow/spacefarm#8]
https://github.com/busyoucow/spacefarm/blob/main/spaceFarm.md#%E4%BD%9C%E7%89%A9%E3%81%AE%E9%81%B8%E6%8A%9E

- 「作物の選択」というセクションタイトルが付いていますがグラムやエネルギーの数値が主になっています。作物リストを目立たせましょう。
- 数字が羅列されていますがこれはリストではなく表に格納しましょう。
- 表はイメージ貼り込みではなく markdown 表に慣れるようにしませんか。

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/76a6717ef6527e3815aaf50d91a60ac716eb7904
こちらにて修正します。

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/76a6717ef6527e3815aaf50d91a60ac716eb7904
こちらにて修正しました。

**Comment by busyoucow** [comment]
https://github.com/busyoucow/spacefarm/commit/76a6717ef6527e3815aaf50d91a60ac716eb7904
こちらにて表にしました。
